apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
spec:
  name: summarize
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: keithcallenberg/text-summarization-seldon:latest
          name: summarize
          resources:
            requests:
              cpu: 0.5
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /health/status
              port: http
              scheme: HTTP
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /health/status
              port: http
              scheme: HTTP
            timeoutSeconds: 1
    - hpaSpec:
        minReplicas: 1
        maxReplicas: 4
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 20